version: "3.1"

services:
  app:
    build: .
    working_dir: /opt/app
    environment:
      GOBARBERDB: gobarber
      GOBARBERPORT: 3000
      GOBARBERDBUSER: postgres
      GOBARBERDBPASSWORD: admin
      GOBARBERDBSERVER: db
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/app
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8090:8080
